# Generated by Django 3.1.5 on 2021-08-04 11:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import embed_video.fields
import webpages.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField(blank=True, null=True)),
                ('title', models.CharField(max_length=255, verbose_name='Topic Of The week')),
                ('question1', models.CharField(max_length=255, verbose_name='Question 1')),
                ('question2', models.CharField(blank=True, max_length=255, verbose_name='Question 2')),
                ('question3', models.CharField(blank=True, max_length=255, verbose_name='Question 3')),
                ('video', embed_video.fields.EmbedVideoField()),
                ('date_posted', models.DateField(auto_now_add=True)),
                ('display_q1', models.CharField(blank=True, editable=False, max_length=255)),
                ('display_q2', models.CharField(blank=True, editable=False, max_length=255)),
                ('display_q3', models.CharField(blank=True, editable=False, max_length=255)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=webpages.models.get_image_filename, verbose_name='images')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_images', to='webpages.post')),
            ],
        ),
    ]
